# Generated by Django 6.0.3 on 2026-03-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_role_agentprofile_booking_chargesheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="service_center_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="service_center_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="service_center_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="service_center_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="booking",
            name="service_center_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
