# Generated by Django 6.0.3 on 2026-03-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_booking_service_center_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentprofile",
            name="expertise",
        ),
    ]
